# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b090d202d1c7318ba73f00fc05c12035178974d72374f236aaf79dee3726e5ce3ea4ba07c154058fedb3aca30342c755706f8f53a9fde5ea6ec24b6fb0d2a788

test:
  secret_key_base: bcec9b7e0313521790ce6d3f01bc1ca273dd8dfe3724bad0d2df7f1aa00c50f0b5afe04c7150d5ea9463056d2ff5d4381c1387e23379d238641e8f5ad17d2221

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
